### PR TITLE
fix: paginationSelector for PDF generation

### LINKED ISSUE #178: PDF file generation INCOMPLETE
The PDF file generation is **creating only the TOC (table of contents) with links to localhost on port 3000** :(

Could this be due to #174?

### PR DESCRIPTION
**Pull request by dadolhay**
closes #178

### CODE REVIEW

**Review by humphd — COMMENTED** [review]
Can you please attach the resulting PDF this generates into the PR discussion, so reviewers can evaluate it?

**Comment by dadolhay** [comment]
Sure!
[Introduction-to-C.pdf](https://github.com/Seneca-ICTOER/Intro2C/files/10058132/Introduction-to-C.pdf)

**Review by humphd — APPROVED** [review]
I think this is working now.  cc @CameronGray1210 for final approval.

NOTE: there is still *so* much to fix about the resulting PDF, and if you have any interest in following up on that, @dadolhay, it would be really valuable.

**Review by CameronGray1210 — APPROVED** [review]
At least it has returned to the full site content, so I would have to say that we can put this one live.

However, I wonder if we should disable the link to the PDF until it's in a more presentable state can be another Issue).  The sample PDF provided is quite incomplete and is compromises the content too much to be worth anyone's time using it (scroll through the content and you will see many blank pages).

I've very much like to continue with getting a PDF generator working though.

**Pull request merged**
