### PR TITLE
chore: Upgrade Docusaurus and related library versions

### LINKED ISSUE #175: Docusaurus is pinned to an outdated beta version
`Docusaurus` and all other libraries it normally ships with should be upgraded to the versions that a fresh `create-docusaurus@latest` project employs

### PR DESCRIPTION
**Pull request by dadolhay**
What does this PR do?

- It upgrades the library versions that `Docusaurus` ships with to the latest versions that work together correctly
- Removes `^` from `@docusaurus/plugin-pwa`. It should always be on the same version as `@docusaurus/core`
- adds `@docusaurus/module-type-aliases` to `devDependencies`, as a new project that is created by `create-docusaurus@latest` includes this, and it seems to be an integral part of the project

Tested with both local development and `build` - `serve`

closes #175

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
So they recommend using pinned versions for Docusaurus?  I notice you're mixing `^` and pinned versions now.

Also, can I get you to look into these warnings (specifically, unmet peer deps, and also the browsersdb update)?

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".
warning " > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning "@docusaurus/plugin-ideal-image > @endiliey/react-ideal-image@0.0.11" has unmet peer dependency "prop-types@>=[15](https://github.com/Seneca-ICTOER/Intro2C/actions/runs/3455836656/jobs/5768612494#step:4:16)".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.7.2" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 41.82s.
yarn run v1.22.[19](https://github.com/Seneca-ICTOER/Intro2C/actions/runs/3455836656/jobs/5768612494#step:4:20)
$ docusaurus build
[INFO] [en] Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[info] [webpackbar] Compiling Client
[info] [webpackbar] Compiling Server
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[success] [webpackbar] Client: Compiled successfully in [30](https://github.com/Seneca-ICTOER/Intro2C/actions/runs/3455836656/jobs/5768612494#step:4:31).06s
[success] [webpackbar] Server: Compiled successfully in [33](https://github.com/Seneca-ICTOER/Intro2C/actions/runs/3455836656/jobs/5768612494#step:4:34).81s
[info] [webpackbar] Compiling Service Worker
[success] [webpackbar] Service Worker: Compiled successfully in 6[38](https://github.com/Seneca-ICTOER/Intro2C/actions/runs/3455836656/jobs/5768612494#step:4:39).69ms
[SUCCESS] Generated static files in "build".
[INFO] Use `npm run serve` command to test your build locally.
Done in 51.83s.
```

**Comment by dadolhay** [comment]
They do pin the following:
- @docusaurus/core
- @docusaurus/preset-classic
- @docusaurus/module-type-aliases

but they do not pin:
- @mdx-js/react
- clsx
- prism-react-renderer
- react
- react-dom

It seems that they do correlated releases of the @docusaurus namespaced libs (they all have the same, 2.2.0 version)


- Caniuse / browsersdb upgrade done


> warning " > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".

File-loader should be (and is) required by `@docusaurus/core`. with the appropriate version. Adding this dependency again into the package.json file caused the warning (with no other effect). Since the newly built version does not contain this dependency in the package.json, I think it can safely be removed (causing no change  other than removing this error)

> warning " > url-loader@4.1.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".

Exact same as above

> warning "@docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".

This warning is present in a freshly deployed install too. They seem to resolve `react-loadable` from `@docusaurus/react-loadable` but it triggers this warning non the less, I think this is expacted behaviour.

> warning "@docusaurus/core > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".

This warning is also present in a fresh deploy, I'd guess this only has an impact if custom components are employed, and they are developed in TS.

> warning "@docusaurus/plugin-ideal-image > @endiliey/react-ideal-image@0.0.11" has unmet peer dependency "prop-types@>=15".

I'm not exactly sure that this [plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image) is in use at all. If it is, it is being run on autopilot. Regardless, adding prop-types would only make sense for custom (non-TS) react components, so I'm not sure if in our case this peer-dep declaration makes sense. May be worth an investigation ticket if this lib is in use at all or not.

> warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.7.2" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6"

This is also present in a fresh install, Seems to be an internal issue to the @algolia project, but it is indeed required by multiple other @algolia scoped package with the correct version

**Review by humphd — APPROVED** [review]
Awesome, nice detective work.

**Comment by humphd** [comment]
@CameronGray1210 this looks good to go from my perspective, but I'll let you have the final say and merge when you're happy.

**Comment by CameronGray1210** [comment]
Yes this is greatly appreciated excellent resolution!

**Review by CameronGray1210 — COMMENTED** [review]
Much needed update and something I was wanting to look into.

**Pull request merged**
